### ISSUE TITLE
crash: rotation + fab-dialog change handler (if rotate while dialog is open)

### ISSUE THREAD

**Issue by Zhuinden** [gumil/navigator-demo#2]
Rotated screen when dialog was open.

                       FATAL EXCEPTION: main
                       Process: io.github.gumil.testnavigator, PID: 19554
                       kotlin.TypeCastException: null cannot be cast to non-null type android.view.ViewGroup
                       at io.github.gumil.testnavigator.changehandler.fab.FabToDialogTransitionChangeHandler.prepareForTransition(FabToDialogTransitionChangeHandler.kt:37)

**Comment by Zhuinden** [comment]
It doesn't crash anymore but it kinda clears elements in the RecyclerView behind it for some reason. 😕

**Comment by gumil** [comment]
This is weird, I've replicated this once, but couldn't replicate it anymore. Does it always happen?

**Comment by Zhuinden** [comment]
Yes. Open the Github icon button dialog, rotate the screen, then press ok. 

About 4 elements out of 5 in the background start looking blue with a Github icon and disappear. It's super weird.

**Comment by gumil** [comment]
Figured it out, I was not restoring the state that's why it's trying to scroll while animating causing that weird animation
